title: idle run
email: me@idle.run
description: >
  Useful notes from a Software Engineer
baseurl: ""
url: "http://www.idle.run"
github_username:  idlerun
markdown: kramdown
repository: github.com/idlerun
excerpt_separator: <!--more-->